print("Python Coding Challenge Arithmetic Operator by Khian Calderon BSIT-1A")
num1 = eval(input("Enter your first number: "))
num2 = eval(input("Enter your second number: "))
print(f"The sum of {num1} and {num2} is {num1 + num2}")
print(f"The difference of {num1} and {num2} is {num1 - num2}")
print(f"The product of {num1} and {num2} is {num1 * num2}")
print(f"The quotient of {num1} and {num2} is {num1 / num2}")
print(f"{num1} Exponent of {num2} is {num1 ** num2}")
print(f"The remainder of {num1} and {num2} is {num1 % num2}")
print(f"The floor division of {num1} and {num2} is {num1 // num2}")